name: Deploy Student App

on:
  push:
    paths:
      - "student_app/**"
      - "Procfile.student"
      - "requirements.txt"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Copy student Procfile
        run: cp Procfile.student Procfile

      - name: Show active Procfile
        run: cat Procfile

      - name: Deploy to Heroku (Student App)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "student-performance-demo"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}